language: ruby
rvm:
  - 2.2.1
branches:
  only:
    - heroku-mongoid
sudo: false
deploy:
  provider: heroku
  api_key: "eb6b1d5f-2db7-4b46-92ba-82bbb447c2a2"
  app: moeri-navigation
  on: heroku-mongoid